name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: konek.vps-poliban.my.id
          username: root
          port: 12197
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/NAUKA-Backend
            echo "Pulling latest changes..."
            git pull 
            
            echo "installing dependencies..."
            composer install --no-dev --optimize-autoloader

            echo "Running migrations..."
            php artisan migrate --force

            echo "Clearing caches..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deployment completed successfully."